version: 2
updates:
  # Root NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # File API sample NPM dependencies
  - package-ecosystem: "npm"
    directory: "/quickstarts/file-api"
    schedule:
      interval: "weekly"

  # File API sample Python dependencies
  - package-ecosystem: "pip"
    directory: "/quickstarts/file-api"
    schedule:
      interval: "weekly"
